---
title: "simsimqt-introduction"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{simsimqt-introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(simsimqt)
```


## Setting up a simulation

```{r}
founder_genotypes <- draw_founder_genotypes(n_ind = 100,
                                            n_loci = 1000,
                                            distribution = "beta",
                                            parameters = list(shape1 = 1/2,
                                                              shape2= 1/2))
```


```{r}
hist(colSums(founder_genotypes)/2/nrow(founder_genotypes))
```


```{r}
trait <- make_trait(founder_genotypes,
                    n_qtl = 50,
                    distribution = "gaussian",
                    parameters = list(mean_a = 0, var_a = 1),
                    Vg = 1)
trait
```

```{r}
simparam <- SimParam$new(traits = list(trait), Ve = 1)
```


```{r}
population <- new_population(founder_genotypes,
                             simparam)
```



```{r}
par(mfrow = c(2, 1))
hist(population$gv)
hist(population$pheno)
```

### Inspecting genotypes at causative variants

```{r}
geno <- pull_qtl_geno(population,
                      1,
                      simparam)
dim(geno)
geno[1:5, 1:5]
```

```{r}
pull_qtl_freq(population,
              1, 
              simparam)
```



## Creating a breeding structure

### Selection

```{r}
selected <- select_ind(population, n_ind = 10)
```

```{r}
fitness_stabilising <- function(trait) {
  
  fitness <- exp(-trait^2)
  
}

selected_stabilising <- select_ind_fitness(population,
                                           trait = 1,
                                           n_ind = 20,
                                           fitness_function = fitness_stabilising)
```



### Mating

```{r}
cross_plan <- cbind(selected$id[selected$sex == "F"][1:2],
                    selected$id[selected$sex == "M"][1:2])
make_cross(selected, cross_plan, n_progeny = 1, simparam = simparam)
```


```{r}
balanced_cross(selected[selected$id[selected$sex == "F"]],
               selected[selected$id[selected$sex == "M"]],
               n_crosses = 2,
               n_progeny = 5,
               simparam = simparam)
```


```{r}
rand_cross2(selected[selected$id[selected$sex == "F"]],
            selected[selected$id[selected$sex == "M"]],
            n_crosses = 20,
            n_progeny = 1,
            simparam = simparam)
```
```{r}
rand_cross(selected,
           n_crosses = 20,
           n_progeny = 1,
           simparam = simparam)
```

```{r}
select_cross_fitness(selected,
                     n_crosses = 20,
                     n_progeny = 1,
                     fitness_function = fitness_stabilising,
                     simparam = simparam)
```



## Setting up a breeding structure

### Directional selection

```{r}
generations <- vector(mode = "list",
                      length = 20)

generations[[1]] <- population

for (gen in 2:20) {
  
  sires <- select_ind(get_males(generations[[gen - 1]]), 
                      n_ind = 10,
                      trait = 1)
                      
  dams <- get_females(generations[[gen - 1]])
  
  generations[[gen]] <- balanced_cross(dams,
                                       sires,
                                       n_crosses = 100,
                                       n_progeny = 1,
                                       simparam = simparam)
  
  
}
```

```{r}
plot(unlist(lapply(generations, meanG)))
```


```{r}
plot(unlist(lapply(generations, varG)))
```



### Stabilising selection

```{r}
generations_stab <- vector(mode = "list",
                           length = 20)

generations_stab[[1]] <- population

for (gen in 2:20) {
  
  generations_stab[[gen]] <-
    select_cross_fitness(generations_stab[[gen - 1]],
                         n_crosses = 100,
                         n_progeny = 1,
                         fitness_function = fitness_stabilising,
                         simparam = simparam)
  
  
}
```

```{r}
plot(unlist(lapply(generations_stab, meanG)))
```


```{r}
plot(unlist(lapply(generations_stab, varG)))
```

