# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_gametes_cpp <- function(g) {
    .Call('_simsimqt_get_gametes_cpp', PACKAGE = 'simsimqt', g)
}

get_inherited_genotype_vector <- function(mother_geno, father_geno) {
    .Call('_simsimqt_get_inherited_genotype_vector', PACKAGE = 'simsimqt', mother_geno, father_geno)
}

